// <auto-generated />
using System;
using GaraCarAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GaraCar.Migrations
{
    [DbContext(typeof(GaraCarContext))]
    partial class GaraCarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GaraCarAPI.Models.CT_HoaDon_DichVu", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaDichVu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DichVuMaDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HoaDonSuaChuaMaHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaHoaDon", "MaDichVu");

                    b.HasIndex("DichVuMaDichVu");

                    b.HasIndex("HoaDonSuaChuaMaHoaDon");

                    b.ToTable("CT_HoaDon_DichVus");
                });

            modelBuilder.Entity("GaraCarAPI.Models.CT_HoaDon_PhuTung", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HoaDonSuaChuaMaHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SanPhamMaSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaHoaDon", "MaSanPham");

                    b.HasIndex("HoaDonSuaChuaMaHoaDon");

                    b.HasIndex("SanPhamMaSanPham");

                    b.ToTable("CT_HoaDon_PhuTungs");
                });

            modelBuilder.Entity("GaraCarAPI.Models.DichVu", b =>
                {
                    b.Property<string>("MaDichVu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDichVu");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("GaraCarAPI.Models.HoaDon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhachHangMaKhachHang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGiaoDuKien")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PhuThu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SanPhamMaSanPham")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("KhachHangMaKhachHang");

                    b.HasIndex("SanPhamMaSanPham");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("GaraCarAPI.Models.HoaDonSuaChua", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaYeuCau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienMaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ThoiGianHoanThanhDuKien")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YeuCauSuaChuaMaYeuCau")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("NhanVienMaNhanVien");

                    b.HasIndex("YeuCauSuaChuaMaYeuCau");

                    b.ToTable("HoaDonSuaChuas");
                });

            modelBuilder.Entity("GaraCarAPI.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKhachHang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CmndCccd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiKhach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgaySinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("GaraCarAPI.Models.LoaiHang", b =>
                {
                    b.Property<string>("MaLoaiHang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenLoaiHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiHang");

                    b.ToTable("LoaiHangs");
                });

            modelBuilder.Entity("GaraCarAPI.Models.NhaCungCap", b =>
                {
                    b.Property<string>("MaNCC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CongTy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhomNCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhuongXa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNCC");

                    b.ToTable("NhaCungCaps");
                });

            modelBuilder.Entity("GaraCarAPI.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CmndCccd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhanVien");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("GaraCarAPI.Models.NhapHang", b =>
                {
                    b.Property<string>("MaNhapHang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhaCungCapMaNCC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SanPhamMaSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Soluong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhapHang");

                    b.HasIndex("NhaCungCapMaNCC");

                    b.HasIndex("SanPhamMaSanPham");

                    b.ToTable("NhapHangs");
                });

            modelBuilder.Entity("GaraCarAPI.Models.PhieuBaoHanh", b =>
                {
                    b.Property<string>("MaPhieuBaoHanh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HoaDonMaHoaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhachHangMaKhachHang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SanPhamMaSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ThoiGianBaoHanh")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPhieuBaoHanh");

                    b.HasIndex("HoaDonMaHoaDon");

                    b.HasIndex("KhachHangMaKhachHang");

                    b.HasIndex("SanPhamMaSanPham");

                    b.ToTable("PhieuBaoHanhs");
                });

            modelBuilder.Entity("GaraCarAPI.Models.SanPham", b =>
                {
                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvatarPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DuKienHetSanPham")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaVon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiHangMaLoaiHang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLoaiHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("TonKho")
                        .HasColumnType("int");

                    b.HasKey("MaSanPham");

                    b.HasIndex("LoaiHangMaLoaiHang");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("GaraCarAPI.Models.SoQuy", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoiTuongNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaTri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiThuChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhieu");

                    b.ToTable("SoQuys");
                });

            modelBuilder.Entity("GaraCarAPI.Models.XeKhachHang", b =>
                {
                    b.Property<string>("BienSoXe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhachHangMaKhachHang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BienSoXe");

                    b.HasIndex("KhachHangMaKhachHang");

                    b.ToTable("XeKhachHangs");
                });

            modelBuilder.Entity("GaraCarAPI.Models.YeuCauSuaChua", b =>
                {
                    b.Property<string>("MaYeuCau")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BienSoXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XeKhachHangBienSoXe")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaYeuCau");

                    b.HasIndex("XeKhachHangBienSoXe");

                    b.ToTable("YeuCauSuaChuas");
                });

            modelBuilder.Entity("GaraCarAPI.Models.CT_HoaDon_DichVu", b =>
                {
                    b.HasOne("GaraCarAPI.Models.DichVu", "DichVu")
                        .WithMany()
                        .HasForeignKey("DichVuMaDichVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaraCarAPI.Models.HoaDonSuaChua", "HoaDonSuaChua")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("HoaDonSuaChuaMaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("HoaDonSuaChua");
                });

            modelBuilder.Entity("GaraCarAPI.Models.CT_HoaDon_PhuTung", b =>
                {
                    b.HasOne("GaraCarAPI.Models.HoaDonSuaChua", "HoaDonSuaChua")
                        .WithMany()
                        .HasForeignKey("HoaDonSuaChuaMaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaraCarAPI.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamMaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDonSuaChua");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("GaraCarAPI.Models.HoaDon", b =>
                {
                    b.HasOne("GaraCarAPI.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("KhachHangMaKhachHang");

                    b.HasOne("GaraCarAPI.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamMaSanPham");

                    b.Navigation("KhachHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("GaraCarAPI.Models.HoaDonSuaChua", b =>
                {
                    b.HasOne("GaraCarAPI.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienMaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaraCarAPI.Models.YeuCauSuaChua", "YeuCauSuaChua")
                        .WithMany("HoaDonSuaChuas")
                        .HasForeignKey("YeuCauSuaChuaMaYeuCau");

                    b.Navigation("NhanVien");

                    b.Navigation("YeuCauSuaChua");
                });

            modelBuilder.Entity("GaraCarAPI.Models.NhapHang", b =>
                {
                    b.HasOne("GaraCarAPI.Models.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("NhaCungCapMaNCC");

                    b.HasOne("GaraCarAPI.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamMaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("GaraCarAPI.Models.PhieuBaoHanh", b =>
                {
                    b.HasOne("GaraCarAPI.Models.HoaDon", "HoaDon")
                        .WithMany("PhieuBaoHanhs")
                        .HasForeignKey("HoaDonMaHoaDon");

                    b.HasOne("GaraCarAPI.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangMaKhachHang");

                    b.HasOne("GaraCarAPI.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamMaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("KhachHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("GaraCarAPI.Models.SanPham", b =>
                {
                    b.HasOne("GaraCarAPI.Models.LoaiHang", "LoaiHang")
                        .WithMany()
                        .HasForeignKey("LoaiHangMaLoaiHang");

                    b.Navigation("LoaiHang");
                });

            modelBuilder.Entity("GaraCarAPI.Models.XeKhachHang", b =>
                {
                    b.HasOne("GaraCarAPI.Models.KhachHang", "KhachHang")
                        .WithMany("XeKhachHangs")
                        .HasForeignKey("KhachHangMaKhachHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("GaraCarAPI.Models.YeuCauSuaChua", b =>
                {
                    b.HasOne("GaraCarAPI.Models.XeKhachHang", "XeKhachHang")
                        .WithMany("YeuCauSuaChuas")
                        .HasForeignKey("XeKhachHangBienSoXe");

                    b.Navigation("XeKhachHang");
                });

            modelBuilder.Entity("GaraCarAPI.Models.HoaDon", b =>
                {
                    b.Navigation("PhieuBaoHanhs");
                });

            modelBuilder.Entity("GaraCarAPI.Models.HoaDonSuaChua", b =>
                {
                    b.Navigation("ChiTietDichVus");
                });

            modelBuilder.Entity("GaraCarAPI.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("XeKhachHangs");
                });

            modelBuilder.Entity("GaraCarAPI.Models.XeKhachHang", b =>
                {
                    b.Navigation("YeuCauSuaChuas");
                });

            modelBuilder.Entity("GaraCarAPI.Models.YeuCauSuaChua", b =>
                {
                    b.Navigation("HoaDonSuaChuas");
                });
#pragma warning restore 612, 618
        }
    }
}
